version: '3.8'

services:
  server:
    build:
      context: ./backEnd
    volumes:
      - ./backEnd/:/backEnd/
    command: python manage.py runserver 0.0.0.0:8000
    # command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backEnd/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backEnd/.env.db
    ports:
      - 5432:5432

volumes:
    postgres_data:
